name: Vyking CI + CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'index.html'
      - 'Dockerfile'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            nimaakhavi/vyking-html:latest
            nimaakhavi/vyking-html:${{ github.sha }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: nimaakhavi/vyking-manifests
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gitops

      - name: Update image tag
        run: |
          sed -i "s|image: nimaakhavi/vyking-html:.*|image: nimaakhavi/vyking-html:${{ github.sha }}|" gitops/vyking/application/template/deployment.yaml
          cd gitops
          git config user.name "nimaakhavi"
          git config user.email "nimaakhavi@gmail.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push
