apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-helm-chart.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "webapp-helm-chart.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "webapp-helm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}