apiVersion: v2
name: infra
description: Infrastructure Helm chart with MySQL and backup cronjob
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: 9.14.4
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled