# Global settings
global:
  namespace: infra

# MySQL configuration (Bitnami MySQL chart)
mysql:
  enabled: true
  serviceName: mysql
  auth:
    rootPassword: mypassword
    database: appdb
    username: user
    password: mypassword
  primary:
    persistence:
      enabled: true
      size: 1Gi
    service:
      type: ClusterIP  # Internal access only
      port: 3306

# Application configuration
app:
  replicateToBackend: true      # Enable secret replication to backend ns
  replicateToFrontend: false    # Set to true if frontend needs DB access
  createBackendNamespace: true  # Auto-create backend namespace
  createFrontendNamespace: true # Auto-create frontend namespace

# Backup configuration
backup:
  enabled: true
  schedule: "*/5 * * * *"
  image:
    repository: bitnami/mysql
    tag: "8.0"
  storage:
    size: 1Gi
  mysql:
    host: mysql
    database: appdb

# Namespace configuration
namespace:
  create: true
  name: infra

#  Network policies for security (optional)
# networkPolicies:
#   enabled: true
#   allowCrossNamespaceAccess: true