apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  index.html: {{ tpl (.Files.Get "configs/index.html") . | indent 4 }}
  nginx.conf: {{ tpl (.Files.Get "configs/nginx.conf") . | indent 4 }}