apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ include "frontend.name" . | quote }}
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "frontend.name" . | quote }}
    {{- include "frontend.selectorLabels" . | nindent 4 }}