replicaCount: 1

image:
  repository: ghcr.io/nimanisha/backend-app 
  tag: latest 
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-login

serviceAccount:
  create: true
  name: ""
  annotations: {}

database:
  host: "infrastructure-db-postgresql.db.svc.cluster.local"
  name: "my_database"
  user: "postgres"
  # port: "5432"
  existingSecret: "my-db-postgresql" 

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

istio:
  enabled: true
  host: "backend.k3d.localhost"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetLatency: "4000m"  
