apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
data:
  DB_NAME: "{{ .Values.database.name }}"