apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backend.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "backend.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Object
    object:
      metric:
        name: istio_requests_latency_p95 
      describedObject:
        apiVersion: networking.istio.io/v1alpha3
        kind: VirtualService
        name: {{ include "backend.fullname" . }}
      target:
        type: Value
        value: {{ .Values.hpa.targetLatency | quote }}