apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "backend.fullname" . }}-mtls
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  mtls:
    mode: STRICT 