{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.istio.host }}
  gateways:
  - istio-system/main-gateway 
  http:
  - route:
    - destination:
        host: {{ include "backend.fullname" . }}
        port:
          number: {{ .Values.service.port }}
      weight: 100
    retries: 
      attempts: 3
      perTryTimeout: 2s