apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
  spec:
    containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.db.configMapName }}
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.db.configMapName }}
                key: DB_NAME
          - name: DB_USRE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secretName }}
                key: DB_USER   
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secretName }}
                key: DB_PASSWORD                                 