# Global settings
global:
  namespace: default

# Frontend application configuration
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.21-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    serverName: "frontend-app"
    backendUrl: "http://webapp-helm-chart-backend:8080"

# Backend application configuration  
backend:
  enabled: true
  replicaCount: 2
  image:
    repository: httpd
    tag: "2.4-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    serverName: "backend-app"
    databaseHost: "mysql"
    databasePort: "3306"
    databaseName: "webapp_db"
    databaseUser: "webapp_user"

# Common configuration
commonConfig:
  environment: "production"
  logLevel: "info"