replicaCount: 2

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
istio:
  enabled: true
  host: "frontend.k3d.localhost"
  mtlsMode: STRICT

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: "frontend-service-account"  


hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPU: 80
  targetLatency: 4000m
ingress:
  enabled: false
  className: "traefik"
  host: "frontend.k3d.localhost" 
  path: /

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

backend:
  namespace: "backend"
  port: 8080

# image:
#   pullPolicy: IfNotPresent
