# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: mysql-backup
#   namespace: infra
# spec:
#   schedule: "*/5 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: backup
#             image: bitnami/mysql:8.0
#             command:
#             - /bin/sh
#             - -c
#             - |
#               TIMESTAMP=$(date +"%Y%m%d%H%M%S")
#               mkdir -p /backups
#               mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /backups/db-$TIMESTAMP.sql
#             env:
#             - name: MYSQL_HOST
#               value: mysql
#             - name: MYSQL_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-credentials
#                   key: user
#             - name: MYSQL_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-credentials
#                   key: password
#             - name: MYSQL_DATABASE
#               value: appdb
#             volumeMounts:
#             - name: backup-volume
#               mountPath: /backups
#           restartPolicy: OnFailure
#           volumes:
#           - name: backup-volume
#             persistentVolumeClaim:
#               claimName: mysql-backup-pvc
