apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ include "demo.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "demo.fullname" . }}-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.images.backend }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.backend.port }}
        env:
        - name: MYSQL_HOST
          value: {{ .Values.env.backend.MYSQL_HOST | quote }}
        - name: MYSQL_PORT
          value: {{ .Values.env.backend.MYSQL_PORT | quote }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: MYSQL_DATABASE
          value: {{ .Values.env.backend.MYSQL_DATABASE | quote }}
