# Main secret in infra namespace
apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DB_HOST: "{{ .Values.mysql.serviceName }}.{{ .Values.global.namespace }}.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: {{ .Values.mysql.auth.database }}
  DB_USER: {{ .Values.mysql.auth.username }}
  DB_PASSWORD: {{ .Values.mysql.auth.password }}

---
# Replicated secret for backend namespace
{{- if .Values.app.replicateToBackend }}
apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
  namespace: default
type: Opaque
stringData:
  DB_HOST: "{{ .Values.mysql.serviceName }}.{{ .Values.global.namespace }}.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: {{ .Values.mysql.auth.database }}
  DB_USER: {{ .Values.mysql.auth.username }}
  DB_PASSWORD: {{ .Values.mysql.auth.password }}
{{- end }}

---
# Replicated secret for frontend namespace (if needed)
# {{- if .Values.app.replicateToFrontend }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-db-credentials
#   namespace: default
# type: Opaque
# stringData:
#   DB_HOST: "{{ .Values.mysql.serviceName }}.{{ .Values.global.namespace }}.svc.cluster.local"
#   DB_PORT: "3306"
#   DB_NAME: {{ .Values.mysql.auth.database }}
#   DB_USER: {{ .Values.mysql.auth.username }}
#   DB_PASSWORD: {{ .Values.mysql.auth.password }}
# {{- end }}